Kubernetes security
otus-kuber-2021-03/Natrofl_platform pull request #5
Opened 2021-04-13 16:25 UTC by Natrofl

дубль два

2021-04-13 16:36 UTC, Jasstkn requested changes
Тесты упали: https://github.com/otus-kuber-2021-03/Natrofl_platform/pull/5/checks?check_run_id=2335397120#step:4:100

2021-04-13 16:45 UTC, Natrofl commented
> Тесты упали: https://github.com/otus-kuber-2021-03/Natrofl_platform/pull/5/checks?check_run_id=2335397120#step:4:100

как интерпретировать этот stdout? результатом выполнения команды kubectl auth can-i get deployments --as system:serviceaccount:dev:jane должно быть значение "no"?

2021-04-14 04:45 UTC, Jasstkn commented
> > Тесты упали: https://github.com/otus-kuber-2021-03/Natrofl_platform/pull/5/checks?check_run_id=2335397120#step:4:100
> 
> как интерпретировать этот stdout? результатом выполнения команды kubectl auth can-i get deployments --as system:serviceaccount:dev:jane должно быть значение "no"?

У jane должны быть права на получение деплойментов в немспейс dev. У вас ответ: no, значит прав нет

2021-04-14 04:46 UTC, Jasstkn commented on kubernetes-security/task03/03-jane-admin.yaml
> +  name: jane
Потеряли тут немспейс из-за этого ваш биндинг в дефолтный применяется

2021-04-14 04:46 UTC, Jasstkn commented on kubernetes-security/task03/05-ken-view.yaml
> +  name: ken
Аналогично

2021-04-14 07:09 UTC, Natrofl commented on kubernetes-security/task03/03-jane-admin.yaml
> +  name: jane
спасибо за подсказку!)

2021-04-14 07:10 UTC, merged

2021-04-14 07:10 UTC, Natrofl commented
тесты пройдены все ок.